### ISSUE TITLE
installation fails on build server

### ISSUE THREAD

**Issue by ghost** [bokuweb/karma-nightmare#18]
### Overview of the problem

I'm using karma-nightmare **version** [0.4.9]

### Description

Can you kindly update the Nightmare package to v2.10.0 as it fixes this issue https://github.com/segmentio/nightmare/issues/1269

**Comment by bokuweb** [comment]
@tosin-ekolie-cko Could you please use v0.4.11. It uses electron v1.7.6.

**Comment by ghost** [comment]
Hi I've updated to v0.4.11 and I'm still getting the same error 

> Error: Failed to find Electron v1.8.0 for linux-x64

v0.4.11 uses Nightmare v2.9.1 and Electron 1.4.4. is dependency, however, Nightmare v2.10.0 has fixed this issue as it also uses electron 1.7.6.

Thanks!

**Comment by bokuweb** [comment]
Hmm, well I'm gonna update nightmare version.
But I think v2.10.0 will not solve this issue because v2.10.0 had released 7month ago.
We need to wait for v2.11.0 or v2.10.1.

**Comment by bokuweb** [comment]
@tosin-ekolie-cko I use nightmare#master for now because fixed version has not published yet...
Could you please use karma-nightmarev0.4.13 for now.
If nightmare published, I'm gonna update it.

**Comment by ghost** [comment]
@bokuweb Thanks. It works now!
